#AMARISOFT MONITORING FRAMEWORK CONFIGURATION
#Controls network node connections, Prometheus exporter, and logging levels.

[Amari]
Callbox=10.205.52.101
MME=9000
ENB=9001
# Maximum number of requests before connection reset
request_limit=20
# Time interval (seconds) between requests
request_interval=5

[CORE]
IP=10.205.52.103
MME=9000
ENB=9001
request_limit=20
request_interval=5

[FIUM_T3]
IP=10.205.52.179
MME=9000
ENB=9001
request_limit=20
request_interval=5

[PCI_503]
IP=10.205.52.184
MME=9000
ENB=9001
request_limit=20
request_interval=5

[Prometheus]
port=8082

[debug]
maxLevel=DEBUG
mode=ERROR
filemode=INFO
file=stats.log
version=1.0